[workspace]
members = ["finanzbuch_lib", "tauri/src-tauri", "flatpak_dep_writer"]
resolver = "2"  # use the newer resolver (since cargo 1.50+)

[profile.release]
lto = "fat"
codegen-units = 4
panic = "unwind"
opt-level = 3
strip = true
incremental = true
