services:
  develop: 
    container_name: finanzbuch

    build:
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ./:/root/project
    
    # keep the container running forever
    command: sh -c 'while true; do sleep 3600; done'
