# run with
# rustup run nightly cargo fmt

unstable_features = true
max_width = 150
imports_granularity = "Item"
brace_style = "AlwaysNextLine"

empty_item_single_line = true
fn_single_line = true
single_line_if_else_max_width = 160
struct_lit_single_line = true
