# building for musl target, means statically linking all used libraries into the binary, so that it can run on all systems that are the same platform
# [build]
# target = "x86_64-unknown-linux-musl"

# static linking can be achieved on different ways while still building for x86_64-unknown-linux-gnu
# target-feature=+crt-static   or    #[cfg(target_feature = "crt-static")]
